name: "Release stable"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci ignore')"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup PHP 8.0"
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.0"
          extensions: "yaml"

      - name: "Get version"
        id: metadata
        run: |
          echo "NEW_VERSION=$(php -r 'echo (version_compare(yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["version"], file_get_contents(__DIR__ + "/version-nukkit.txt"), ">") ? "y" : "n");')" >> $GITHUB_OUTPUT
          echo "VERSION=$(php -r 'echo explode("+", explode("-", yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["version"])[0])[0];')" >> $GITHUB_OUTPUT
          echo "FULL_VERSION=$(php -r 'echo yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["version"];')" >> $GITHUB_OUTPUT
          echo "NAME=$(php -r 'echo yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["name"];')" >> $GITHUB_OUTPUT

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: "maven"

      - name: "Build with Maven"
        run: mvn -B package --file pom.xml

      - name: "Rename JAR"
        run: |
          cd target/
          cp Nukkit-1.0-SNAPSHOT.jar Presence-Man-Nukkit-v${{ steps.metadata.outputs.VERSION }}.jar
          cp Nukkit-1.0-SNAPSHOT.jar Presence-Man-Nukkit.jar
          cd ../

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          automatic_release_tag: "v${{ steps.metadata.outputs.VERSION }}"
          prerelease: false
          title: "Release v${{ steps.metadata.outputs.VERSION }}"
          files: "target/**.jar"

      - name: "Create version-nukkit.txt"
        if: "${{ steps.metadata.outputs.NEW_VERSION }} === 'y'"
        run: "echo \"${{ steps.metadata.outputs.VERSION }}\" > version-nukkit.txt"

      - name: "Update version.txt"
        uses: "test-room-7/action-update-file@v1"
        if: "${{ steps.metadata.outputs.NEW_VERSION }} === 'y'"
        with:
          file-path: version-nukkit.txt
          commit-msg: Updated version - ci ignore
          github-token: ${{ secrets.GITHUB_TOKEN }}
          committer-name: "xxAROX"
          committer-email: "arox.email.0@gmail.com"

      #- name: "Pushes latest version-nukkit.txt file"
      #  uses: dmnemec/copy_file_to_another_repo_action@main
      #  env:
      #    API_TOKEN_GITHUB: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      #  with:
      #    source_file: 'version-nukkit.txt'
      #    destination_repo: 'Presence-Man/releases'
      #    destination_folder: ''
      #    user_email: 'arox.email.0@gmail.com'
      #    user_name: 'xxAROX'
      #    commit_message: 'Updated "Nukkit Client" version'

      #- name: Release to public
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: "latest"
      #    name: "Latest releases"
      #    repository: "Presence-Man/releases"
      #    token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      #    files: "target/Presence-Man-Nukkit.jar"
